"""non_unique_fields_in_user_table

Revision ID: 2172f2acf9f8
Revises: bc5c300019a7
Create Date: 2023-07-01 15:59:59.824694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2172f2acf9f8'
down_revision = 'bc5c300019a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_phone_key', 'users', type_='unique')
    op.drop_constraint('users_tg_id_key', 'users', type_='unique')
    op.drop_constraint('users_tg_username_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_tg_username_key', 'users', ['tg_username'])
    op.create_unique_constraint('users_tg_id_key', 'users', ['tg_id'])
    op.create_unique_constraint('users_phone_key', 'users', ['phone'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    # ### end Alembic commands ###
