"""cascade delete

Revision ID: 60738b5705eb
Revises: 574af7e85640
Create Date: 2023-06-19 18:46:33.602592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60738b5705eb'
down_revision = '574af7e85640'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('basket_products_basket_id_fkey', 'basket_products', type_='foreignkey')
    op.drop_constraint('basket_products_product_id_fkey', 'basket_products', type_='foreignkey')
    op.create_foreign_key(None, 'basket_products', 'baskets', ['basket_id'], ['id'])
    op.create_foreign_key(None, 'basket_products', 'products', ['product_id'], ['id'])
    op.drop_constraint('products_category_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_category_id_fkey', 'products', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'basket_products', type_='foreignkey')
    op.drop_constraint(None, 'basket_products', type_='foreignkey')
    op.create_foreign_key('basket_products_product_id_fkey', 'basket_products', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('basket_products_basket_id_fkey', 'basket_products', 'baskets', ['basket_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
