"""basket product quantity int add

Revision ID: 792d7369e1a1
Revises: 9fb4360613a2
Create Date: 2023-06-20 20:13:39.572909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '792d7369e1a1'
down_revision = '9fb4360613a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basket_products', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('basket_products', 'quantity')
    # ### end Alembic commands ###
