"""add on delete cascade user id on table token_block_list

Revision ID: ac8a7f427e32
Revises: daf688c14d69
Create Date: 2023-06-05 13:39:15.409275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac8a7f427e32'
down_revision = 'daf688c14d69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('token_blocklist_user_id_fkey', 'token_blocklist', type_='foreignkey')
    op.create_foreign_key(None, 'token_blocklist', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(None, 'token_blocklist', type_='foreignkey')
    op.create_foreign_key('token_blocklist_user_id_fkey', 'token_blocklist', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
