"""add unit price in order_product

Revision ID: bc5c300019a7
Revises: 67e113cf0e01
Create Date: 2023-06-27 20:05:27.874240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc5c300019a7'
down_revision = '67e113cf0e01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_products', sa.Column('unit_price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_products', 'unit_price')
    # ### end Alembic commands ###
